### ISSUE TITLE
Shots travel forever, should disappear when they go off screen.

### ISSUE THREAD

**Issue by zygoth** [colindt/unity-platformer#8] opened 2015-03-26 20:51 UTC

**Comment by joe-eklund** [comment] 2015-03-31 00:40
Has this been fixed? It looks like you fixed it in one of your pushes? Just double checking before I closed this issue.

**Comment by zygoth** [comment] 2015-03-31 02:51
Yeah it's fixed.

**Comment by JeffreyAngell** [comment] 2015-03-31 02:55
Not fully. There are certain spots I can still cause the error.

**Comment by zygoth** [comment] 2015-03-31 02:57
Where?

**Comment by JeffreyAngell** [comment] 2015-03-31 03:09
At least in the prototype level. Let me see if I can do it elsewhere.

**Comment by zygoth** [comment] 2015-03-31 03:14
Are you sure you have pulled recently?  Whenever I shoot I can see in the
hierarchy on the left that the shot disappeared when it went off screen.

**Comment by JeffreyAngell** [comment] 2015-03-31 03:16
Yes. That's what I usually see, but there are spots where they don't disappear from the list.

**Comment by JeffreyAngell** [comment] 2015-03-31 03:18
Okay, it appears to be when the shots are shot from off the screen. I can reproduce it in any level, but it may only be because I can force myself to be off the screen. When we fix that issue, I think this will never happen.

**Comment by joe-eklund** [comment] 2015-03-31 03:19
Oh so if you are shooting while traveling around (Like from bottom to top, or left to right) then the bullets stay in the object list?

**Comment by joe-eklund** [comment] 2015-03-31 03:21
I can confirm Jeff's findings that when your character is off screen that happens.

**Comment by zygoth** [comment] 2015-03-31 03:21
Ok, that does make sense.  I'll take care of that tomorrow.

**Comment by zygoth** [comment] 2015-03-31 03:23
Ok, that does make sense.  The shot disappears when it goes from being
visible to being not visible, but if it's never visible in the first place
it could travel forever.  You could just make a check in the awake() method
to check if you started off screen or not.

**Comment by joe-eklund** [comment] 2015-03-31 03:29
I'm done working on this tonight. So feel free to push anything you want.

**Comment by zygoth** [comment] 2015-03-31 03:30
Ok, I'll probably fix this tomorrow then if nobody else does before then.

**Comment by colindt** [comment] 2015-04-03 05:16
I think we verified that this was fixed.

**Closed as completed by colindt** 2015-04-03 05:16 UTC
